# Generated by Django 4.2.7 on 2023-11-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cartitem_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
